Repository Eight-Corner/camp24_web, pull requests merged in 2022-06, with the labels that each got.

#21 test-commit1
  src/views/Main.js
Labels: good first issue

#22 20 frontend services 구조 개발
  package-lock.json
  package.json
  src/assets/scss/common.scss
  src/services/api.config.js
  src/services/config.js
  src/services/index.js
  src/services/request.js
  src/views/Main.js
Labels: Develop, 진행중

#24 config api url
  src/services/config.js
Labels: Develop, 진행중

#23 18 front react 메인 퍼블리싱
  src/App.js
  src/App.test.js
  src/assets/css/App.css
  src/assets/css/index.css
  src/assets/css/reset.css
  src/assets/scss/header.scss
  src/assets/scss/icon.scss
  src/components/Footer.jsx
  src/components/Header.jsx
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/views/Main.js
  src/views/Main.jsx
Labels: Develop, 진행중, 확인 완료중
